// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CredentialRegistry$Type } from "./CredentialRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CredentialRegistry"]: CredentialRegistry$Type;
    ["contracts/CredentialRegistry.sol:CredentialRegistry"]: CredentialRegistry$Type;
  }

  interface ContractTypesMap {
    ["CredentialRegistry"]: GetContractReturnType<CredentialRegistry$Type["abi"]>;
    ["contracts/CredentialRegistry.sol:CredentialRegistry"]: GetContractReturnType<CredentialRegistry$Type["abi"]>;
  }
}
